# Generated by Django 4.2.17 on 2025-01-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='name',
        ),
    ]
