# Generated by Django 4.2.17 on 2025-02-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='embedding',
            field=models.JSONField(default=None, null=True),
        ),
    ]
