# Generated by Django 4.2.17 on 2025-02-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
        ('complaints', '0002_complaint_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cluster',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster'),
        ),
    ]
