# Generated by Django 4.2.17 on 2025-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='y',
            field=models.FloatField(default=0.0),
        ),
    ]
