# Generated by Django 4.2.17 on 2025-01-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_item_alter_complaint_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='name',
            field=models.CharField(default='Unnamed Complaint', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Unnamed Complaint', max_length=100),
        ),
    ]
