# Generated by Django 4.2.17 on 2025-01-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_name_alter_complaint_text_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
