# Generated by Django 4.2.17 on 2025-04-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('complaints', '0004_alter_complaint_x_alter_complaint_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
    ]
