# Generated by Django 4.2.17 on 2025-01-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_point_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.IntegerField(),
        ),
    ]
