# Generated by Django 4.2.17 on 2025-01-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_point_x_alter_point_y'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.CharField(default='No Email', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
