# Generated by Django 4.2.17 on 2025-04-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('complaints', '0006_alter_complaint_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
    ]
