# Generated by Django 4.2.17 on 2025-04-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0009_alter_cluster_project'),
        ('projects', '0001_initial'),
        ('complaints', '0007_alter_complaint_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cluster',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.cluster'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='projects.project'),
        ),
    ]
