# Generated by Django 4.2.17 on 2025-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cluster',
            field=models.CharField(default='Unnamed Cluster', max_length=100),
        ),
    ]
