# Generated by Django 4.2.17 on 2025-06-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0009_alter_cluster_project'),
        ('complaints', '0008_alter_complaint_cluster_alter_complaint_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='cluster',
        ),
        migrations.AddField(
            model_name='complaint',
            name='clusters',
            field=models.ManyToManyField(blank=True, to='clusters.cluster'),
        ),
    ]
