# Generated by Django 4.2.17 on 2025-06-14 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0009_alter_cluster_project'),
        ('complaints', '0009_remove_complaint_cluster_complaint_clusters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='clusters',
        ),
        migrations.AddField(
            model_name='complaint',
            name='cluster',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.cluster'),
        ),
    ]
