# Generated by Django 4.2.17 on 2025-02-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
        ('complaints', '0009_alter_complaint_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='cluster',
        ),
        migrations.AddField(
            model_name='complaint',
            name='clusters_field',
            field=models.ForeignKey(default='2023-10-05 14:30:00', on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-05 14:30:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
