# Generated by Django 4.2.17 on 2025-02-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='complaints_field',
        ),
    ]
