# Generated by Django 4.2.17 on 2025-03-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_alter_cluster_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='model',
            field=models.CharField(default='GigaChat', max_length=50),
        ),
    ]
