# Generated by Django 4.2.17 on 2025-04-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('clusters', '0004_cluster_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='model',
            field=models.CharField(default='No model', max_length=50),
        ),
    ]
