# Generated by Django 4.2.17 on 2025-04-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0005_cluster_project_alter_cluster_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
