# Generated by Django 4.2.17 on 2025-04-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('clusters', '0005_cluster_project_alter_cluster_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='project',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
    ]
