# Generated by Django 4.2.17 on 2025-04-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0006_cluster_size'),
        ('clusters', '0007_alter_cluster_project'),
    ]

    operations = [
    ]
