# Generated by Django 4.2.17 on 2025-04-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('clusters', '0008_merge_0006_cluster_size_0007_alter_cluster_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='projects.project'),
        ),
    ]
